/**
 * Created by martin on 27.04.2016.
 */

import Languages from '/imports/lib/schemas/general/languages';

export default function () {

      if (Languages.find().count() == 0) {

            Languages.insert({ language: "Abkhazian", langCode: "ab" });
            Languages.insert({ language: "Afar", langCode: "aa" });
            Languages.insert({ language: "Afrikaans", langCode: "af" });
            Languages.insert({ language: "Albanian", langCode: "sq" });
            Languages.insert({ language: "Amharic", langCode: "am" });
            Languages.insert({ language: "Arabic", langCode: "ar" });
            Languages.insert({ language: "Aragonese", langCode: "an" });
            Languages.insert({ language: "Armenian", langCode: "hy" });
            Languages.insert({ language: "Assamese", langCode: "as" });
            Languages.insert({ language: "Aymara", langCode: "ay" });
            Languages.insert({ language: "Azerbaijani", langCode: "az" });
            Languages.insert({ language: "Bashkir", langCode: "ba" });
            Languages.insert({ language: "Basque", langCode: "eu" });
            Languages.insert({ language: "Bengali (Bangla)", langCode: "bn" });
            Languages.insert({ language: "Bhutani", langCode: "dz" });
            Languages.insert({ language: "Bihari", langCode: "bh" });
            Languages.insert({ language: "Bislama", langCode: "bi" });
            Languages.insert({ language: "Breton", langCode: "br" });
            Languages.insert({ language: "Bulgarian", langCode: "bg" });
            Languages.insert({ language: "Burmese", langCode: "my" });
            Languages.insert({ language: "Byelorussian (Belarusian)", langCode: "be" });
            Languages.insert({ language: "Cambodian", langCode: "km" });
            Languages.insert({ language: "Catalan", langCode: "ca" });
            Languages.insert({ language: "Chinese", langCode: "zh" });
            Languages.insert({ language: "Chinese (Simplified)", langCode: "zh-Hans" });
            Languages.insert({ language: "Chinese (Traditional)", langCode: "zh-Hant" });
            Languages.insert({ language: "Corsican", langCode: "co" });
            Languages.insert({ language: "Croatian", langCode: "hr" });
            Languages.insert({ language: "Czech", langCode: "cs" });
            Languages.insert({ language: "Danish", langCode: "da" });
            Languages.insert({ language: "Dutch", langCode: "nl" });
            Languages.insert({ language: "English", langCode: "en", sortTop: true});
            Languages.insert({ language: "Esperanto", langCode: "eo" });
            Languages.insert({ language: "Estonian", langCode: "et" });
            Languages.insert({ language: "Faeroese", langCode: "fo" });
            Languages.insert({ language: "Farsi", langCode: "fa" });
            Languages.insert({ language: "Fiji", langCode: "fj" });
            Languages.insert({ language: "Finnish", langCode: "fi" });
            Languages.insert({ language: "French", langCode: "fr", sortTop: true});
            Languages.insert({ language: "Frisian", langCode: "fy" });
            Languages.insert({ language: "Galician", langCode: "gl" });
            Languages.insert({ language: "Gaelic (Scottish)", langCode: "gd" });
            Languages.insert({ language: "Gaelic (Manx)", langCode: "gv" });
            Languages.insert({ language: "Georgian", langCode: "ka" });
            Languages.insert({ language: "German", langCode: "de" , sortTop: true});
            Languages.insert({ language: "Greek", langCode: "el" });
            Languages.insert({ language: "Greenlandic", langCode: "kl" });
            Languages.insert({ language: "Guarani", langCode: "gn" });
            Languages.insert({ language: "Gujarati", langCode: "gu" });
            Languages.insert({ language: "Haitian Creole", langCode: "ht" });
            Languages.insert({ language: "Hausa", langCode: "ha" });
            Languages.insert({ language: "Hebrew", langCode: "he, iw" });
            Languages.insert({ language: "Hindi", langCode: "hi" });
            Languages.insert({ language: "Hungarian", langCode: "hu" });
            Languages.insert({ language: "Icelandic", langCode: "is" });
            Languages.insert({ language: "Ido", langCode: "io" });
            Languages.insert({ language: "Indonesian", langCode: "id, in" });
            Languages.insert({ language: "Interlingua", langCode: "ia" });
            Languages.insert({ language: "Interlingue", langCode: "ie" });
            Languages.insert({ language: "Inuktitut", langCode: "iu" });
            Languages.insert({ language: "Inupiak", langCode: "ik" });
            Languages.insert({ language: "Irish", langCode: "ga" });
            Languages.insert({ language: "Italian", langCode: "it", sortTop: true });
            Languages.insert({ language: "Japanese", langCode: "ja" });
            Languages.insert({ language: "Javanese", langCode: "jv" });
            Languages.insert({ language: "Kannada", langCode: "kn" });
            Languages.insert({ language: "Kashmiri", langCode: "ks" });
            Languages.insert({ language: "Kazakh", langCode: "kk" });
            Languages.insert({ language: "Kinyarwanda (Ruanda)", langCode: "rw" });
            Languages.insert({ language: "Kirghiz", langCode: "ky" });
            Languages.insert({ language: "Kirundi (Rundi)", langCode: "rn" });
            Languages.insert({ language: "Korean", langCode: "ko" });
            Languages.insert({ language: "Kurdish", langCode: "ku" });
            Languages.insert({ language: "Laothian", langCode: "lo" });
            Languages.insert({ language: "Latin", langCode: "la" });
            Languages.insert({ language: "Latvian (Lettish)", langCode: "lv" });
            Languages.insert({ language: "Limburgish ( Limburger)", langCode: "li" });
            Languages.insert({ language: "Lingala", langCode: "ln" });
            Languages.insert({ language: "Lithuanian", langCode: "lt" });
            Languages.insert({ language: "Macedonian", langCode: "mk" });
            Languages.insert({ language: "Malagasy", langCode: "mg" });
            Languages.insert({ language: "Malay", langCode: "ms" });
            Languages.insert({ language: "Malayalam", langCode: "ml" });
            Languages.insert({ language: "Maltese", langCode: "mt" });
            Languages.insert({ language: "Maori", langCode: "mi" });
            Languages.insert({ language: "Marathi", langCode: "mr" });
            Languages.insert({ language: "Moldavian", langCode: "mo" });
            Languages.insert({ language: "Mongolian", langCode: "mn" });
            Languages.insert({ language: "Nauru", langCode: "na" });
            Languages.insert({ language: "Nepali", langCode: "ne" });
            Languages.insert({ language: "Norwegian", langCode: "no" });
            Languages.insert({ language: "Occitan", langCode: "oc" });
            Languages.insert({ language: "Oriya", langCode: "or" });
            Languages.insert({ language: "Oromo (Afaan Oromo)", langCode: "om" });
            Languages.insert({ language: "Pashto (Pushto)", langCode: "ps" });
            Languages.insert({ language: "Polish", langCode: "pl" });
            Languages.insert({ language: "Portuguese", langCode: "pt" });
            Languages.insert({ language: "Punjabi", langCode: "pa" });
            Languages.insert({ language: "Quechua", langCode: "qu" });
            Languages.insert({ language: "Rhaeto-Romance", langCode: "rm" });
            Languages.insert({ language: "Romanian", langCode: "ro" });
            Languages.insert({ language: "Russian", langCode: "ru" });
            Languages.insert({ language: "Samoan", langCode: "sm" });
            Languages.insert({ language: "Sangro", langCode: "sg" });
            Languages.insert({ language: "Sanskrit", langCode: "sa" });
            Languages.insert({ language: "Serbian", langCode: "sr" });
            Languages.insert({ language: "Serbo-Croatian", langCode: "sh" });
            Languages.insert({ language: "Sesotho", langCode: "st" });
            Languages.insert({ language: "Setswana", langCode: "tn" });
            Languages.insert({ language: "Shona", langCode: "sn" });
            Languages.insert({ language: "Sichuan Yi", langCode: "ii" });
            Languages.insert({ language: "Sindhi", langCode: "sd" });
            Languages.insert({ language: "Sinhalese", langCode: "si" });
            Languages.insert({ language: "Siswati", langCode: "ss" });
            Languages.insert({ language: "Slovak", langCode: "sk" });
            Languages.insert({ language: "Slovenian", langCode: "sl" });
            Languages.insert({ language: "Somali", langCode: "so" });
            Languages.insert({ language: "Spanish", langCode: "es" });
            Languages.insert({ language: "Sundanese", langCode: "su" });
            Languages.insert({ language: "Swahili (Kiswahili)", langCode: "sw" });
            Languages.insert({ language: "Swedish", langCode: "sv" });
            Languages.insert({ language: "Tagalog", langCode: "tl" });
            Languages.insert({ language: "Tajik", langCode: "tg" });
            Languages.insert({ language: "Tamil", langCode: "ta" });
            Languages.insert({ language: "Tatar", langCode: "tt" });
            Languages.insert({ language: "Telugu", langCode: "te" });
            Languages.insert({ language: "Thai", langCode: "th" });
            Languages.insert({ language: "Tibetan", langCode: "bo" });
            Languages.insert({ language: "Tigrinya", langCode: "ti" });
            Languages.insert({ language: "Tonga", langCode: "to" });
            Languages.insert({ language: "Tsonga", langCode: "ts" });
            Languages.insert({ language: "Turkish", langCode: "tr" });
            Languages.insert({ language: "Turkmen", langCode: "tk" });
            Languages.insert({ language: "Twi", langCode: "tw" });
            Languages.insert({ language: "Uighur", langCode: "ug" });
            Languages.insert({ language: "Ukrainian", langCode: "uk" });
            Languages.insert({ language: "Urdu", langCode: "ur" });
            Languages.insert({ language: "Uzbek", langCode: "uz" });
            Languages.insert({ language: "Vietnamese", langCode: "vi" });
            Languages.insert({ language: "Volapük", langCode: "vo" });
            Languages.insert({ language: "Wallon", langCode: "wa" });
            Languages.insert({ language: "Welsh", langCode: "cy" });
            Languages.insert({ language: "Wolof", langCode: "wo" });
            Languages.insert({ language: "Xhosa", langCode: "xh" });
            Languages.insert({ language: "Yiddish", langCode: "yi, ji" });
            Languages.insert({ language: "Yoruba", langCode: "yo" });
            Languages.insert({ language: "Zulu", langCode: "zu" });


            console.log("startup.js says: Languages  " + Languages.find().count());
      }
}